---
# Source: frigate/charts/frigate/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate
  namespace: frigate
  labels:
    app.kubernetes.io/name: frigate
    helm.sh/chart: frigate-7.0.3
    app.kubernetes.io/instance: frigate
    app.kubernetes.io/managed-by: Helm
data:
  config.yml: |
    mqtt:
      # Required: host name
      host: mqtt.server.com
      # Optional: port (default: shown below)
      port: 1883
      # Optional: topic prefix (default: shown below)
      # WARNING: must be unique if you are running multiple instances
      topic_prefix: frigate
      # Optional: client id (default: shown below)
      # WARNING: must be unique if you are running multiple instances
      client_id: frigate
      # Optional: user
      user: mqtt_user
      # Optional: password
      # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
      #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
      password: password
      # Optional: interval in seconds for publishing stats (default: shown below)
      stats_interval: 60
    
    detectors:
      # coral:
      #   type: edgetpu
      #   device: usb
      cpu1:
        type: cpu
    
    # cameras:
    #   # Name of your camera
    #   front_door:
    #     ffmpeg:
    #       inputs:
    #         - path: rtsp://{FRIGATE_RSTP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@10.0.10.10:554/cam/realmonitor?channel=1&subtype=2
    #           roles:
    #             - detect
    #             - rtmp
    #     width: 1280
    #     height: 720
    #     fps: 5
