apiVersion: v2
name: victoria-metrics-taylor
description: An Umbrella Helm chart for deploying victoria-metrics
# Custom field for application-generator
namespace: taylor-monitoring
# Custom field for application-generator - compatibility with the old victoria-metrics helm deployment
releaseName: victoria-metrics
type: application
version: "0.0.1"
appVersion: "0.31.0"
dependencies:
  - name: victoria-metrics-single
    version: "0.31.0"
    repository: "https://victoriametrics.github.io/helm-charts/"
