---
# Source: tank-monitor/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-tank-monitor
  namespace: test-taylor-monitoring
  labels:
    app: test-tank-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-tank-monitor
  template:
    metadata:
      labels:
        app: test-tank-monitor
    spec:
      containers:
      - name: test-tank-monitor
        image: syoder89/tank-monitor:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SENSOR
          value: "taylor_water_tank_level1"
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 64Mi
