---
# Source: tank-monitor/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-tank-monitor
  namespace: test-taylor-monitoring
  labels:
    app: test-tank-monitor
spec:
  selector:
    app: test-tank-monitor
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
---
# Source: tank-monitor/templates/service.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: test-tank-monitor
  namespace: test-taylor-monitoring
  labels:
    app: test-tank-monitor
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: test-tank-monitor
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
