---
# Source: stock-ticker/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-stock-ticker
  annotations:
    operator.1password.io/auto-restart: "true"
  labels:
    app: test-stock-ticker
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: test-stock-ticker
  template:
    metadata:
      labels:
        app: test-stock-ticker
      annotations:
        checksum/config: 542c0acbc2f41c28cd53560bca8b735344d93bcfe1dede047648dcfa59033f3b
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
      containers:
      - name: test-stock-ticker
        image: us-central1-docker.pkg.dev/personal-356214/stock-ticker/stock-ticker:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        envFrom:
        - configMapRef:
            name: test-stock-ticker
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: stock-ticker-api-credentials
              key: credential
        - name: GOMEMLIMIT
          valueFrom:
            resourceFieldRef:
              resource: requests.memory
        ports:
        - name: http
          containerPort: 8080
        startupProbe:
          httpGet:
            path: /startupz
            port: http
          failureThreshold: 30
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
          periodSeconds: 10
          failureThreshold: 3
        resources:
          limits:
            memory: 32Mi
          requests:
            cpu: 8m
            memory: 32Mi
