---
# Source: stock-ticker/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-ticker
  namespace: stock-ticker
  labels:
    app: stock-ticker
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: stock-ticker
  template:
    metadata:
      labels:
        app: stock-ticker
      annotations:
        checksum/config: 04d52f7e99aac8a57b397c78145b7f812c13f6a1423c517e326722ba9d5ae5c1
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
      containers:
      - name: stock-ticker
        image: us-central1-docker.pkg.dev/personal-356214/stock-ticker/stock-ticker:20260410-b3091f6
        imagePullPolicy: IfNotPresent
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        envFrom:
        - configMapRef:
            name: stock-ticker
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: stock-ticker-api-credentials
              key: credential
        - name: GOMEMLIMIT
          valueFrom:
            resourceFieldRef:
              resource: requests.memory
        ports:
        - name: http
          containerPort: 8080
        startupProbe:
          httpGet:
            path: /startupz
            port: http
          failureThreshold: 30
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
          periodSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 64Mi
