---
# Source: stock-ticker/templates/secret.yaml
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: stock-ticker-api-credentials
spec:
  itemPath: "vaults/homelab/items/stock-ticker-api-credentials"
