apiVersion: v2
name: tank-monitor
description: Umbrella Helm chart for tank-monitor - MQTT water level sensor to VictoriaMetrics
namespace: taylor-monitoring
type: application
version: "0.1.0"
appVersion: "latest"

imageSubscriptions:
- repoURL: us-central1-docker.pkg.dev/personal-356214/tank-monitor/tank-monitor
  tagSelectionStrategy: Lexicographic
  allowTags: ^\d{8}-[0-9a-f]{7}$
  discoveryLimit: 10
  valuesKey: image.tag
