image:
  repository: syoder89/tank-monitor
  tag: latest
sensor: taylor_water_tank_level1
broker: tcp://mosquitto:1883
vmPushURL: http://victoria-metrics-victoria-metrics-single-server:8428/api/v1/import/prometheus
otlpEndpoint: tempo.observability:4317
probeAddr: ":8080"
